name: Prepare offline task

on:
  workflow_dispatch:

jobs:
  prepare-offline-task:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/typescript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: mkdir -p tmp && echo '${{ secrets.GH_COOKIE }}' > ./tmp/github.com.cookies.json
      - run: npm run run:prepare-offline-task
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
