name: Prepare offline task

on:
  workflow_dispatch:

jobs:
  prepare-offline-task:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/typescript
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci
      - run: mkdir -p tmp && ./node_modules/.bin/gh-cookie "$GH_ACCOUNT_NAME" "$GH_PASSWORD" "$GH_AUKEY" > ./tmp/github.com.cookies.json
        env:
          GH_ACCOUNT_NAME: ${{ secrets.GH_ACCOUNT_NAME }}
          GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
          GH_AUKEY: ${{ secrets.GH_AUKEY }}
      - run: npm run run:prepare-offline-task
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
