name: Prepare offline task

on:
  workflow_dispatch:

jobs:
  prepare-offline-task:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/typescript
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: mkdir -p tmp && npx -y gh-cookie '${{ secrets.GH_ACCOUNT_NAME }}' '${{ secrets.GH_PASSWORD }}' '${{ secrets.GH_AUKEY }}' > ./tmp/github.com.cookies.json
      - run: npm run run:prepare-offline-task
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
